using alps.net.api.ALPS;
using alps.net.api.StandardPASS;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ALPS_Visio_AddIn_rewrite.OWLShapes.Layout
{
    /// <summary>
    /// Resolves explicit ontology bounds or the bounds generated by the fallback
    /// layout for one model element.
    /// </summary>
    internal static class VisioBoundsProvider
    {
        public static List<ISimple2DVisualizationPoint> GetBounds(
            PASSProcessModelElement element)
        {
            if (VisioLayout.TryGetGeneratedBounds(
                element, out List<ISimple2DVisualizationPoint> generatedBounds))
            {
                return generatedBounds;
            }

            List<ISimple2DVisualizationPoint> bounds =
                new List<ISimple2DVisualizationPoint>(
                    element.getElementsWithUnspecifiedRelation().Values
                        .OfType<ISimple2DVisualizationPoint>());

            if (bounds.Count < 2)
            {
                throw new InvalidOperationException(
                    "Missing visualisation bounds for "
                    + element.getModelComponentID() + ".");
            }

            return bounds;
        }
    }
}
